ci: supress pybind11 stubtest error
Mypy's `stubtest` command is returning the following error:

```console
me@user:~$ MYPYPATH=src poetry run stubtest nqm.irimager
error: nqm.irimager.IRImager is inconsistent, metaclass differs
Stub: in file src/nqm/irimager/__init__.pyi:11
N/A
Runtime:
<class 'pybind11_builtins.pybind11_type'>
```

This is because pybind11 adds a metaclass to all classes it creates,
and in our type stubs, we can't document this metaclass since it's
internal only.

In CI, we can just ignore this error, and only fail CI if there are
other errors.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,6 +25,17 @@ jobs:
       - name: Check whether nqm.irimager stubs match implementation
         env:
           MYPYPATH: src
-        run: poetry run stubtest nqm.irimager
+        run: |
+          stubtest_output="$(poetry run stubtest nqm.irimager || true)"
+          if echo $stubtest_output \
+            | grep '^error' \
+            | grep --invert-match 'error: nqm.irimager.IRImager is inconsistent, metaclass differs'; then
+
+            echo "::error ::Stubtest returned unexpected errors, ${stubtest_output}"
+            exit 1
+          else
+            # no unexpected errors
+            exit 0
+          fi
       - name: Test with pytest
         run: poetry run pytest
